---
name: Continuous Integration

on:
    pull_request:
    push:
        branches:
            - '*'
            - '*/*'
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
                  fetch-depth: 1

            - name: Setup .env
              run: cp .env.example .env

            - name: Validate docker compose config
              run: docker compose config
